version: '3.8'

services:
  rabbit-mq:
    image: 'rabbitmq:3.9.29-management'
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - credit-network
    
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.2'
    ports:
      - '8081:8080'
    volumes:
      - ./docker/keycloak/:/opt/keycloak/data/import/
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - credit-network
      
networks:
  credit-network:
    driver: bridge