spring:
   application:
      name: ms-customer
      
server:
   port: 0

eureka:
   instance:
      instance-id: ${spring.application.name}:${spring.cloud.application.instance_id:${random.value}}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://eureka-user:usr-eureka@localhost:8761/eureka
