spring:
   application:
      name: ms-card
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      
server:
   port: 0

eureka:
   instance:
      instance-id: ${spring.application.name}:${spring.cloud.application.instance_id:${random.value}}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://eureka-user:usr-eureka@localhost:8761/eureka
         
mq:
  queues:
    card-issuance: card-issuance
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log